[package]
name = "streamers"
version = "0.1.0"
authors = ["Declan Kelly <dkelly.home@gmail.com>"]

[dependencies]
error-chain = "0.11.0"
bytes = "0.4.5"

[dev-dependencies]
criterion = "0.1.1"
unicode-segmentation = "1.2.0"

[[bench]]
name = "radix_tree_benches"
harness = false